language: python
python:
  - 2.7

install:
  - python setup.py install

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
notifications:
  email: 
    - mohamed@kuicr.kyoto-u.ac.jp